---
- hosts: client
  become: yes
  roles:
    - client

- hosts: dataserver
  become: yes
  roles:
    - xrootd
    - dataserver

- hosts: redirector
  become: yes
  roles:
    - xrootd
    - redirector
