---
 - name: allow timedout release file
   template:
    src: apt0.conf.j2
    dest: /etc/apt/apt.conf
   when: http_proxy is defined

# - name: force http proxy
#   template:
#    src: apt.conf.j2
#    dest: /etc/apt/apt.conf
#   when: http_proxy != "none"

# - name: overwrite /etc/apt/sources.list
#   template:
#    src: sources.list.j2
#    dest: /etc/apt/sources.list

 - name: update APT
   apt:
    update_cache: no
    cache_valid_time: 3600 #one hour cache
   become_method: sudo
   register: updated

 - name: upgrade APT
   apt:
     upgrade: yes
     update_cache: yes
   become_method: sudo
   when: updated.changed

 - name: install required packages
   package:
     name:
      - libcap2-bin
      - firewalld
      - dbus
      - init-system-helpers
      - iptables
      - policykit-1
      - python3
      - python3-dbus
      - python3-gi
      - python3-slip-dbus
      - unzip
      - cmake
      - gcc
      - g++
      - git
      - openssl
      - libssl-dev
      - uuid-dev
      - libsqlite3-dev
      - pkg-config
      - zlib1g-dev
      - libcurl4-gnutls-dev
