---
# - name: Copy server.cer
#   template:
#    src: "secrets/server.cer"
#    dest: /usr/local/share/ca-certificates/server.crt

 - name: Creates directories
   file:
    path: "{{item}}"
    state: directory
    owner: xrootd
    group: xrootd
    mode: 0777
   with_items:
     - "/etc/xrootd"
     - "/xrdmnt"
     - "/xrdmnt/data_1/"
     - "/xrdmnt/data_2/"
     - "/xrdmnt/data_1/{{ansible_hostname}}/"
     - "/var/run/xrootd"

 - name: Provision config file for xrootd
   template:
    src: "server_http.cf.j2"
    dest: /etc/xrootd/xrootd.cf
    owner: xrootd
    group: xrootd

 - name: copy testfile
   copy:
    src: testfile
    dest: "{{item}}"
    owner: xrootd
    group: xrootd
   with_items:
     - "/xrdmnt/testfile{{ansible_hostname}}"
     - "/xrdmnt/data_1/testfile{{ansible_hostname}}"
     - "/xrdmnt/data_2/testfile{{ansible_hostname}}"
     - "/xrdmnt/data_1/{{ansible_hostname}}/testfile{{ansible_hostname}}"

 - name: Enable xrootd services
   service:
    daemon_reload: yes
    name: "{{ item }}@xrootd"
    enabled: true
   with_items:
    - xrootd
    - cmsd

 - name: restart xrootd services
   service:
    daemon_reload: yes
    name: "{{ item }}@xrootd"
    state: restarted
   with_items:
     - xrootd
     - cmsd
